### PR TITLE
Update to purescript-test-unit v.12.0.0

### PR DESCRIPTION
**Pull request by Unisay**

### CODE REVIEW

**Comment by coot** [comment]
Thanks, I added a test for `testSkip`.

**Comment by Unisay** [comment]
Thanks! That was quick

**Comment by Unisay** [comment]
Could you pls also create a git version tag so that bower fetches the latest version? Thanks.

**Comment by coot** [comment]
Good point, let's bump the version.

**Comment by coot** [comment]
Done [pursuit](https://pursuit.purescript.org/packages/purescript-karma-test-unit/1.1.0)

**Pull request merged**
